spawnlocation:
    vectorx: 0.0
    vectory: 3.0
    vectorz: 0.0
itemfallspeed:
    velocityx: 0.0
    velocityy: 0.1
    velocityz: 0.0
particle-effect: HAPPY_VILLAGER
#Possible Effects: ANGRY_VILLAGER,ELECTRIC_SPARK,SNOWFLAKE,SHRIEK,HEART_PARTICLE,EXPLOSION_EMITTER, also others as long as they rely on the same Syntax
repeats: 1
particle-count: 10
particle-offsetX: 0.5
particle-offsetY: 0.5
particle-offsetZ: 0.5
particle-speed: 0.1

